version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '${MINIO_PORT}:9000'
      - "9001:9001"
    volumes:
      - './.minio:/data'
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=pass
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET}:public
